import unittest
import os
import sys
import json
import time

from pathlib import Path
from dotenv import load_dotenv
from retriever.models import ConversationState

# Ensure project root is in path
sys.path.append(str(Path(__file__).parent.parent))

# Load environment variables
load_dotenv()

from agent.generator import build_system_instructions, generate_response

class MockGeminiResponse:
    def __init__(self, text):
        self.text = text

class MockClient:
    def __init__(self, response_text):
        class Models:
            def generate_content(self, *args, **kwargs):
                return MockGeminiResponse(response_text)
        self.models = Models()

class TestResponseGenerator(unittest.TestCase):
    def test_build_system_instructions(self):
        state = ConversationState(
            user_message="help",
            conversation_history=[],
            intent="recommend",
            confidence=0.9,
            role="Java Dev",
            job_level=None,
            skills=[],
            constraints={},
            job_description=None,
            previous_recommendations=[],
            missing_fields=["job_level"]
        )
        
        clarify_prompt = build_system_instructions("CLARIFY", state)
        self.assertIn("FSM STATE: CLARIFY", clarify_prompt)
        self.assertIn("job_level", clarify_prompt)
        
        compare_prompt = build_system_instructions("COMPARE", state)
        self.assertIn("FSM STATE: COMPARE", compare_prompt)

    def test_mock_generate_response_merging(self):
        # Retrieved products
        retrieved = [
            {
                "entity_id": "111",
                "name": "Verify GSA",
                "description": "General Ability Test",
                "metadata": {
                    "duration": "30 minutes",
                    "languages": ["English", "Spanish"],
                    "url": "https://shl.com/gsa"
                }
            },
            {
                "entity_id": "222",
                "name": "OPQ32",
                "description": "Personality Questionnaire",
                "metadata": {
                    "duration": "45 minutes",
                    "languages": ["English"],
                    "url": "https://shl.com/opq"
                }
            }
        ]
        
        # Mock Gemini response returning linguistic explanations
        gemini_output = {
            "response": "Here is a balanced battery of tests for your hiring needs.",
            "reasons_for_recommendations": [
                {"entity_id": "111", "reason": "This cognitive test evaluates general problem solving."},
                {"entity_id": "222", "reason": "This personality test measures workplace behavior."}
            ],
            "clarifying_question": None
        }
        
        mock_client = MockClient(json.dumps(gemini_output))
        state = ConversationState(
            user_message="I need a test for software engineer",
            conversation_history=[],
            intent="recommend",
            confidence=0.95,
            role="Software Engineer",
            job_level="Graduate",
            skills=[],
            constraints={},
            job_description=None,
            previous_recommendations=[]
        )
        
        agent_res = generate_response("RETRIEVE", state, retrieved, mock_client)
        
        # Verify next state is mapped directly from python argument, not Gemini
        self.assertEqual(agent_res.next_state, "RETRIEVE")
        self.assertEqual(agent_res.response, gemini_output["response"])
        self.assertEqual(len(agent_res.recommended_products), 2)
        
        # Verify authoritative metadata is preserved (not hallucinated)
        gsa_details = next(p for p in agent_res.recommended_products if p.entity_id == "111")
        self.assertEqual(gsa_details.name, "Verify GSA")
        self.assertEqual(gsa_details.url, "https://shl.com/gsa")
        self.assertEqual(gsa_details.duration, "30 minutes")
        self.assertEqual(gsa_details.languages, ["English", "Spanish"])
        # Verify reason was generated by Gemini
        self.assertEqual(gsa_details.reason_for_recommendation, "This cognitive test evaluates general problem solving.")

    def test_live_generate_response(self):
        api_key = os.getenv("GEMINI_API_KEY")
        if not api_key:
            self.skipTest("GEMINI_API_KEY not found in environment. Skipping live response generation test.")
            
        from google import genai
        client = genai.Client(api_key=api_key)
        
        state = ConversationState(
            user_message="Looking for coding tests for a Python developer",
            conversation_history=[],
            intent="recommend",
            confidence=0.95,
            role="Python Developer",
            job_level="Senior",
            skills=["Python", "Algorithms"],
            constraints={},
            job_description=None,
            previous_recommendations=[],
            missing_fields=[]
        )
        
        # 1. Test CLARIFY State
        state_clarify = ConversationState(
            user_message="Hiring a developer",
            conversation_history=[],
            intent="recommend",
            confidence=0.95,
            role="Developer",
            job_level=None,
            skills=[],
            constraints={},
            job_description=None,
            previous_recommendations=[],
            missing_fields=["job_level"]
        )
        agent_res_clarify = generate_response("CLARIFY", state_clarify, [], client)
        self.assertEqual(agent_res_clarify.next_state, "CLARIFY")
        self.assertIsNotNone(agent_res_clarify.clarifying_question)
        print(f"\nLive Clarifying Question: {agent_res_clarify.clarifying_question}")
        
        # Pace requests to avoid API spikes
        time.sleep(2.0)

        # 2. Test RETRIEVE State
        retrieved_mock = [
            {
                "entity_id": "python_test",
                "name": "Python (New)",
                "description": "Multi-choice test that measures python knowledge.",
                "metadata": {
                    "duration": "30 minutes",
                    "languages": ["English"],
                    "url": "https://shl.com/python-test"
                }
            }
        ]
        agent_res_retrieve = generate_response("RETRIEVE", state, retrieved_mock, client)
        self.assertEqual(agent_res_retrieve.next_state, "RETRIEVE")
        self.assertEqual(len(agent_res_retrieve.recommended_products), 1)
        self.assertEqual(agent_res_retrieve.recommended_products[0].name, "Python (New)")
        self.assertIsNotNone(agent_res_retrieve.recommended_products[0].reason_for_recommendation)
        print(f"Live Reason: {agent_res_retrieve.recommended_products[0].reason_for_recommendation}")

if __name__ == "__main__":
    unittest.main()
